[package]
name = "a"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
eframe = "0.33.0"
egui_extras = { version = "*", features = ["all_loaders"]}
image = { version = "0.25.8", features = ["jpeg", "png"]}
rand = "0.9.2"
